name: gdr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - pandas
  - numpy
  - groq
  - langchain
  - chromadb
  - python-dotenv
  - tiktoken
  - transformers
  - scikit-learn
  - sentence-transformers
 - pip
 - pip:
     - google-generativeai
#    - langchain_pinecone
#    - langchain_community
